apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: platform-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/respoamit/platform-app
    path: platform-app
    targetRevision: main
    helm: 
      valueFiles:
        - values.yaml
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated: {}
