apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: platform-dev
  namespace: argocd
spec:
  project: default
  source:
    directory:
      recurse: true 
    repoURL: https://github.com/respoamit/platform-app.git
    path: platform-app
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
